# -*- coding: utf-8 -*-
"""Untitled82.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMSTJoe4c4FmdTLrdOXVNot0kmnvuCL-
"""

# Load necessary libraries
library(dplyr)

# Load the dataset
data <- read.csv("/content/csew1314teachingopen.csv")

# View the structure of the dataset to identify the 'antisocx' variable
str(data)

# Summary statistics for the 'antisocx' variable
summary_antisocx <- data %>%
  summarise(
    count = n(),
    mean = mean(antisocx, na.rm = TRUE),
    median = median(antisocx, na.rm = TRUE),
    sd = sd(antisocx, na.rm = TRUE),
    min = min(antisocx, na.rm = TRUE),
    max = max(antisocx, na.rm = TRUE),
    na_count = sum(is.na(antisocx))
  )

# Print the summary statistics
print(summary_antisocx)